#! /bin/sh

mkdir -p /tmp/check4StephdlUpdates.$$
TMPFILE=`mktemp /tmp/check4StephdlUpdates.$$/XXXXXXXXXX` || exit 1
TMP1=`mktemp /tmp/check4StephdlUpdates.$$/XXXXXXXXXX` || exit 1
DOMAIN=$(/sbin/e-smith/db configuration get DomainName)|| exit 1

MAILADDR="root admin@$DOMAIN"

yum -e 0 -d 0 check-update --disablerepo=* --enablerepo=stephdl,stephdl-dolibarr,stephdl-roundcubemail > $TMP1
if [ $? = 100 ]; then
  echo -e "===\n=== Yum reports available updates for Stephdl repository :\n===" >> $TMPFILE
  cat $TMP1 >> $TMPFILE
 echo -e "\n    To apply all the updates of stephdl repository, you can log on your server and run the following command :\n
    yum update --enablerepo=stephdl\n\n
    To apply all the updates of roundcubemail repository, you can log on your server and run the following command :\n
    yum update --enablerepo=stephdl-roundcubemail\n\n
    To apply all the updates of dolibarr repository, you can log on your server and run the following command :\n
    yum update --enablerepo=stephdl-dolibarr\n\n
===\n=== Donation : \n===\n
    All my development work is done in my free time and from my own expenses. The softwares are free for you, but not the hardware to develop them.
    If you consider my work as something helpful, thank you to kindly make a donation and allow me to continue paying my server and all associated costs.
    Every euros make the difference, please consider the recurring donation if you earn your living with my softwares.

    https://mirror.de-labrusse.fr/doku.php#donation" >> $TMPFILE
fi

if [ -s $TMPFILE ]; then
  if [ "$1" = "-m" ]; then
    mail -s "Stephdl Updates available for `hostname`" $MAILADDR < $TMPFILE
  else
    echo "Stephdl Updates available for `hostname`"
    cat $TMPFILE
  fi
fi

rm -f $TMPFILE $TMP1
rm -fr /tmp/check4StephdlUpdates.*
