#! /bin/sh

mkdir -p /tmp/check4StephdlUpdates.$$
TMPFILE=`mktemp /tmp/check4StephdlUpdates.$$/XXXXXXXXXX` || exit 1
TMP1=`mktemp /tmp/check4StephdlUpdates.$$/XXXXXXXXXX` || exit 1
DOMAIN=$(/sbin/e-smith/db configuration get DomainName)|| exit 1

MAILADDR=admin@$DOMAIN

yum -e 0 -d 0 check-update --disablerepo=* --enablerepo=stephdl > $TMP1
if [ $? = 100 ]; then
  echo -e "===\n=== yum reports available updates for Stephdl repository :\n===" >> $TMPFILE
  cat $TMP1 >> $TMPFILE
 echo -e "\n    To apply all these updates, you can log on your server and run the following command :\n
    yum update --enablerepo=stephdl\n" >> $TMPFILE
fi

if [ -s $TMPFILE ]; then
  if [ "$1" = "-m" ]; then
    mail -s "Stephdl Updates available for `hostname`" $MAILADDR < $TMPFILE
  else
    echo "Stephdl Updates available for `hostname`"
    cat $TMPFILE
  fi
fi

rm -f $TMPFILE $TMP1
rm -fr /tmp/check4StephdlUpdates.*
