#!/usr/bin/perl

use strict;
use esmith::Build::CreateLinks qw(:all);

my $event = "nethserver-stephdl-update";
event_actions($event, 'initialize-default-databases' => '00');
templates2events("/etc/sudoers", $event);
templates2events("/etc/yum.repos.d/stephdl.repo", $event);
