#!/bin/sh

/sbin/e-smith/check4StephdlUpdates -m >/dev/null 2>&1
EXITVALUE=$?
if [ $EXITVALUE != 0 ]; then
    /usr/bin/logger -t check4StephdlUpdates "ALERT exited abnormally with [$EXITVALUE]"
fi
exit 0

