#!/usr/bin/perl
use strict;
use warnings;
use JSON;
use NethServer::ApiTools;
use LWP::Simple qw (head);

my $input = NethServer::ApiTools::readInput();
my $cmd = $input->{'action'};
my $ret = {};
my $url = 'http://mirror.de-labrusse.fr';
my $head = `/usr/bin/curl -I $url --connect-timeout 2 --max-time 5`;

if ( $cmd eq "app-info") {
    if ($head =~ 'Location: http://mirror.de-labrusse.fr/doku.php') {
            $ret = {
                'name' => "Stephdl is online",
                'url' => "https://mirror.de-labrusse.fr",
                'description' => "You can support the stephane de Labrusse (stephdl) software repository by clicking on the button",
                'summary' => "You can support the stephane de Labrusse (stephdl) software repository by clicking on the button"
            };
        }
        else {
            $ret = {
                'name' => "Stephdl is offline",
                'url' => "https://mirror.de-labrusse.fr",
                'description' => "The stephane de Labrusse (stephdl) repository seems to be offline",
                'summary' => "The stephane de Labrusse (stephdl) repository seems to be offline"
            };
        }
} else {
    NethServer::ApiTools::error();
}

print encode_json($ret);
